###############################################################################
#
# Agent Configuration
#
###############################################################################

AGENT_VERSION="0.1.0"

MONITOR_URL=""

SEND_DATA=0

ICEWARP_HOME="/opt/icewarp"

OUTPUT_JSON="${PROJECT_ROOT}/output/health.json"
